moov-io/infra

envs/sbx/infra/16-kube-state-metrics.yml
envs/sbx/infra/17-cadvisor.yml
envs/sbx/infra/18-node-exporter.yml
lib/infra/14-prometheus.yml
lib/infra/16-kube-state-metrics.yml
lib/infra/17-cadvisor.yml
lib/infra/18-node-exporter.yml

tl;dr This adds alerts and more graphs.
- Alerts: https://infra.moov.io/prometheus/alerts (We can route these to Slack)
- Graphs: https://infra.moov.io/grafana/
kube-state-metrics is a kubernetes service which is designed to pick
up cluster stats. It's pretty common to see deployed.
Link: https://github.com/kubernetes/kube-state-metrics
kubernetes-monitoring is a Github org with some k8s and Prometheus
folks who are working on a good set of alerts and dashboards for k8s installs.
Link: https://github.com/kubernetes-monitoring/kubernetes-mixin
Example graphs:

metrics and graphs (via node-exporter and cAdvisor)

---

.travis.yml
images/oauth2_proxy/Dockerfile
images/oauth2_proxy/makefile
images/test.sh
makefile

Go 1.8 is pretty old (Feb '17), so we should use a more modern Go. Doubly so because this is exposed to the public internet. 
Issue: https://github.com/moov-io/infra/issues/25

images/oauth2_proxy: compile code with Go 1.11.x instead of 1.8.x

---

cmd/dockertest/main.go
images/tarsnap/Dockerfile

Also, 
```
cmd/dockertest: show docker build output on failure
Previously we would overwrite stderr/stdout because of a shared bytes.Buffer. 
CombinedOutput properly joins the two streams for us.
```

images/tarsnap: fixup image build failure

---

images/fsftp/Dockerfile
images/fsftp/README.md
images/fsftp/makefile

I'm going to use this image in local dev and dev environments to serve as an FTP server for paygate to interact with.
Issue: https://github.com/moov-io/paygate/issues/88

images/fsftp: quick docker image for FTP server in a docker image

---

images/tarsnap/Dockerfile

See: https://golang.org/doc/go1.13

images/tarsnap: upgrade to Debian 10

---

images/kube-ingress-index/Dockerfile
images/kube-ingress-index/makefile
makefile

From https://github.com/Banno/kube-ingress-index/releases/tag/0.6.2

images/kube-ingress-index: add docker image from upstream code releases

---

go/lint-project.sh
makefile

With larger sets of files (not sure how many, just ran into this with
Identity) passing them all as arguments in one call exceeds the line
length for a bash command. Let's break up big commands where we can.

go/lint: handle larger sets of files

---

lib/apps/13-watchman.yml

We're on MySQL, so we don't need this mount. Also, ReadWriteOnce
prevents concurrnet mounts.

apps/watchman: remove mount of watchman-data PVC

---

modules/customers/deployment.tf
modules/customers/secrets.tf
modules/customers/variables.tf

This adds support for configuring MySQL in Customers and hiding the transit encryption key with a Secret.

modules/customers: support secrets for transit and mysql configs

---

go/lint-project.sh

We can write a timestamp that will cause nancy to skip the version
check against GitHub. This call gets ratelimited quickly across all of
the Actions runners.
Example: https://github.com/moov-io/ach/runs/1816420912
See: https://github.com/sonatype-nexus-community/nancy/blob/v1.0.10/README.md#big-ci-note

Ignore nancy version checks

---

go/lint-project.sh

In a team's standup today it came up that we need to inspect builds for a specific dependency and ensure always on the latest available. This reminded me that we need to reject moovfinancial dependencies in moov-io projects.

go/lint: reject moovfinancial dependencies in go.mod files

---

modules/kube-state-metrics/rbac.tf

Found this when looking at logs today.

modules/kube-state-metrics: add missing RBAC rule for additional deployments apiGroup

---

go/lint-project.sh

Upgrade nancy. Checked release notes for interceding versions [1.0.13](https://github.com/sonatype-nexus-community/nancy/releases/tag/v1.0.13), [1.0.14,](https://github.com/sonatype-nexus-community/nancy/releases/tag/v1.0.14) and [1.0.15](https://github.com/sonatype-nexus-community/nancy/releases/tag/v1.0.15) and nothing seemed breaking. Ran locally:
```
$ ./go/lint-project.sh
nancy version 1.0.15
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Summary                      ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━┫
┃ Audited Dependencies    ┃ 24 ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━┫
┃ Vulnerable Dependencies ┃ 0  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━┛
finished nancy check
```

go/lint: upgrade nancy from v1.0.12 to v1.0.15

---

lib/infra/18-node-exporter.yml
modules/node-exporter/variables.tf

New version available of Prometheus Node Exporter. See the [v1.1.1 tag](https://quay.io/repository/prometheus/node-exporter?tab=tags). There don't seem to be any breaking changes regarding config, etc. in the two interceding release docs ([v1.1.0](https://github.com/prometheus/node_exporter/releases/tag/v1.1.0), [v1.1.1](https://github.com/prometheus/node_exporter/releases/tag/v1.1.1)) so we should be good to bump.
This change was applied and checked in a staging environment:
```
~ image                      = "quay.io/prometheus/node-exporter:v1.0.1" -> "quay.io/prometheus/node-exporter:v1.1.1
Apply complete!
```

infra/node-exporter: upgrade v1.0.1 to v1.1.1

---

go/lint-project.sh

Upgrade golangci-lint. [No breaking changes](https://github.com/golangci/golangci-lint/releases/). Successful local run:
```
% ./go/lint-project.sh
golangci/golangci-lint info checking GitHub for tag 'v1.37.1'
golangci/golangci-lint info found version: 1.37.1 for v1.37.1/darwin/amd64
golangci/golangci-lint info installed ./bin/golangci-lint
golangci-lint has version 1.37.1 built from b39dbcd6 on 2021-02-20T11:48:06Z
finished golangci-lint check
```

go/lint: upgrade golangci-lint from 1.36.0 to 1.37.1

---

go/lint-project.sh

Upgrade staticcheck. [No breaking changes](https://staticcheck.io/changes/2020.2#2020.2.2) and local run works fine:
```
project.sh
staticcheck 2020.2.2 (v0.1.2)
finished staticcheck check
```

go/lint: upgrade staticcheck from 2020.2.1 to 2020.2.2

---

lib/infra/15-grafana.yml
modules/grafana/variables.tf

Upgrade grafana to [v7.4.3](https://hub.docker.com/layers/grafana/grafana/7.4.3/images/sha256-848c405bb116d5cb1f9de98ebb6f02aec4fbaa8e624ef3fa8824d28a55c09183?context=explore). Breaking changes from [interceding releases](https://github.com/grafana/grafana/releases/):
> Constant variables
> In order to minimize the confusion with Constant variable usage, we've removed the ability to make Constant variables visible. This change will also migrate all existing visible Constant variables to Textbox variables because which we think this is a more appropriate type of variable for this use case.
> Issue #29407
> 
> Plugin compatibility
> We have upgraded AngularJS from version 1.6.6 to 1.8.2. Due to this upgrade some old angular plugins might stop working and will require a small update. This is …

infra/grafana: upgrade from v7.3.7 to 7.4.3

---

modules/cadvisor/variables.tf

[No breaking changes](https://github.com/google/cadvisor/releases/).

infra/cadvisor: Upgrade from v0.37.0 to v0.37.5

---

lib/apps/12-paygate-mysql.yml
lib/apps/13-watchman-mysql.yml
lib/apps/16-customers-mysql.yml

Bump cloud-mysql-backup version in OSS environment. paygate and customers don't seem to have mysql-backup deployed but I upgraded the tag in those YAMLs as well.
```
% kubectl diff -f ../../lib/apps/13-watchman-mysql.yml 
@@ -73,7 +73,7 @@
-            image: adamdecaf/mysql-backup:2020-07-09-01
+            image: gcr.io/maynard-io-public/kubernetes-cloud-mysql-backup:v2.5.0
```
Will ```kubectl apply -f``` for the watchman backup cronjob once this is approved.

envs/oss: upgrade kubernetes-cloud-mysql-backup from v2.3.0 to v2.5.0

---

lib/infra/14-prometheus.yml
modules/prometheus/variables.tf

[Release notes; no breaking changes.](https://github.com/prometheus/prometheus/releases) Will apply changes to OSS environment once this is merged.
```
% kubectl diff -f ./infra/14-prometheus.yml
-        image: prom/prometheus:v2.24.1
+        image: prom/prometheus:v2.25.0
```

infra/prometheus: Upgrade from v2.24.1 to v2.25.0

---

modules/traefik/deployment.tf

With the current configuration Traefik deployments will result in new pods being stuck in `ContainerCreating`:
```
Warning  FailedAttachVolume  4m46s  attachdetach-controller  Multi-Attach error for volume "pvc-[redacted]" Volume is already used by pod(s) traefik-[redacted]
```
Scaling the old ReplicaSet to 0 or scaling the deployment to 0 then re-applying via `terraform` solves the issue as it frees the pvc in question up for use by the new pod. The change of deployment strategy to [Recreate](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment) accomplishes this idiomatically.

modules/traefik: Change deployment to use Recreate strategy

---

modules/cadvisor/daemonset.tf

See https://github.com/moov-io/infra/pull/173#issuecomment-786783315. / was already mounted and matched the default configuration generated by [running kustomize from the cadvisor repo](https://github.com/google/cadvisor/tree/master/deploy/kubernetes). This change makes the container privileged and fixes the error. No logs are generated and the container now has access to /dev/kmsg (as verified by getting shell inside of it and `tail`ing it).

modules/cadvisor: Make container privileged to allow access to OOM events

---

modules/traefik/deployment.tf

Paygate is configured as follows:
```
strategy {
rolling_update {
max_unavailable = 1
}
}
```
... and it destroys all pods before scheduling new ones. I applied this to traefik with the change that max_unavailable is set to `var.replicas` for the case that we have more than one someday.

modules/traefik: Revert to Rolling strategy with maxUnavailable = replicas

---

go/lint-project.sh

Two one-liners. Local run:
```
running go linters for osx
finished gofmt check
misspell version: 0.3.4
finished misspell check
staticcheck 2020.2.3 (v0.1.3)
finished staticcheck check
nancy version 1.0.17
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Summary                      ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━┫
┃ Audited Dependencies    ┃ 24 ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━┫
┃ Vulnerable Dependencies ┃ 0  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━┛
finished nancy check
golangci/golangci-lint info checking GitHub for tag 'v1.37.1'
golangci/golangci-lint info found version: 1.37.1 for v1.37.1/darwin/amd64
golangci/golangci-lint info installed ./bin/golangci-lint
golangci-lint has version 1.37.1 built from b39dbcd6 on 2021-02-20T11:48:06Z
finished golangci-lint check
finished gocyclo check
? …
```

Upgrade nancy and staticcheck

---

lib/apps/10-achfuzz.yml
lib/apps/17-imagecashletterfuzz.yml
lib/apps/18-wirefuzz.yml
lib/apps/19-metro2fuzz.yml
lib/apps/20-iso8583fuzz.yml

OOMKilled a container when attempting to download fuzzer results:
```
$ ./1-download.sh 
command terminated with exit code 137
$ kdp -n apps imagecashletterfuzz-[REDACTED]
Name:                 imagecashletterfuzz-[REDACTED]
Namespace:            apps
Containers:
imagecashletterfuzz:
State:          Running
Started:      Thu, 18 Mar 2021 12:08:57 -0700
Last State:     Terminated
Reason:       OOMKilled
Exit Code:    2
Started:      Thu, 18 Mar 2021 01:29:12 -0700
Finished:     Thu, 18 Mar 2021 12:08:55 -0700
Ready:          True
Restart Count:  50
Limits:
cpu:     400m
memory:  110Mi
Requests:
cpu:        200m
memory:     50Mi
Environment:  <none>
```
Bumping memory limits to 300M should only cost us (300 - 110) * 5 ~= 1GB of memory tops.

Increase fuzzer memory limits to 300M

---

go/lint-project.sh

Indicate that go cyclo is running so it's easily understand when a files functions complexity if above the threshold.

indicate start of gocyclo

---

.github/workflows/go.yml
go/lint-project.sh

Each project can opt-in to threshold checking inside their workflow. 
```yaml
- name: Check
env:
COVER_THRESHOLD: 85.0
run: make check
```

go/lint: add optional check for code coverage threshold

---

go/lint-project.sh

Go 1.17 introduced a migration with build constraints and they offer a migration with gofmt
See https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md#transition for more details

go/lint: go fix pkger files

---

go/lint-project.sh

Dunno if this will work as I've had errors when moving flags before the sub-command, but their code reads like this will work.
https://github.com/sonatype-nexus-community/nancy/blob/533b797f2a7c14d2c9306785e8a92b3c66d41c46/internal/cmd/root.go#L194
We could also set `SKIP_UPDATE_CHECK=true` in the linter script.
https://github.com/sonatype-nexus-community/go-sona-types/blob/main/configuration/set.go#L237

go/lint: specify nancy flags properly

---

go/lint-project.sh

Right now we're seeing the following deprecation warning
```
golangci/golangci-lint info checking GitHub for tag 'v1.42.1'
golangci/golangci-lint info found version: 1.42.1 for v1.42.1/linux/amd64
golangci/golangci-lint info installed ./bin/golangci-lint
golangci/golangci-lint err this script is deprecated, please do not use it anymore. check https://github.com/goreleaser/godownloader/issues/207
golangci-lint has version 1.42.1 built from 54f4301d on 2021-09-06T17:05:10Z
```

go/lint: move off of deprecated goreleaser script

---

go/lint-project.sh

This has been previously enabled on some repositories as an opt-in basis along with some required linters. However we are pushing to enable `gosec` on all repositories. 
To try this out for yourself modify your repository's Makefile:
```
GOLANGCI_LINTERS=gosec ./lint-project.sh
```
See: https://golangci-lint.run/usage/linters/

go/lint: enable more linters by default

---

.github/workflows/go.yml
.gitignore
go/lint-project.sh
makefile

You can view reports with the following command:
```
go tool pprof gofuzz.test -web ./pkg/gofuzz/cpu.out
```

go/lint: support profiling each package during testing

---

.gitignore
go/lint-project.sh

Releases: https://github.com/zricethezav/gitleaks/releases

go/lint: update gitleaks to v8.0.0

---

go/lint-project.sh

We had a build with the follow result from grepping
```
github.com/moov/secret-project/pkg/summary.go:22:				Subtotal			100.0%
total:										(statements)			80.8%
```

go/lint: find the coverage total with a better regex

---

go/lint-project.sh

- [durationcheck](https://github.com/charithe/durationcheck): "detect cases where two time.Duration values are being multiplied in possibly erroneous ways"
- [nolintlint](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/nolintlint/README.md): "find ill-formed or insufficiently explained // nolint directives for golangci"

go/lint: enable durationcheck and nolintlint

---

go/lint-project.sh

There is a flag to configure this, but it's deprecated:
https://github.com/golangci/golangci-lint/blob/7bbbe77e5e68cdbecad5e25fc44810afd8f3d48c/pkg/commands/run.go#L154-L155
```
if [[ $GOLANGCI_FLAGS == "" ]];
then
GOLANGCI_FLAGS="--gocyclo.min-complexity=50"
fi
```
```
Flag --gocyclo.min-complexity has been deprecated, flag will be removed soon, please, use .golangci.yml config
```
So we should just remove this. Setting `.golangci.yml` isn't something I want moov-io/infra's script to deal with.

go/lint: remove gocyclo linter

---

go/lint-project.sh

This extends on the work from https://github.com/moov-io/infra/pull/251  (and https://github.com/sonatype-nexus-community/nancy/issues/228)
However, nancy requires the format of ".Path .Version" in the output, so we can force `go list` to output that. 
See: https://github.com/golang/go/issues/27900

go/lint: only pass deps in our final binary to nancy

---

go/lint-project.sh

Docs: https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck

go/lint: start running govulncheck on moov-io repositories

---

go/lint-project.sh

Seeing failures: https://github.com/moov-io/wire/actions/runs/3004051492/attempts/1

go/lint: call full path for govulncheck, if found

---

go/lint-project.sh

I was reviewing the [linters available in golangci-lint](https://golangci-lint.run/usage/linters/) and figured we could enable some more. 
- [dupword](https://github.com/Abirdcfly/dupword): A linter that checks for duplicate words in the source code
- [errchkjson](https://github.com/breml/errchkjson): Checks types passed to the json encoding functions.
- [exportloopref](https://github.com/kyoh86/exportloopref): An analyzer that finds exporting pointers for loop variables.
- [forcetypeassert](https://github.com/gostaticanalysis/forcetypeassert): Finds type assertions which did forcely such as below.
- [thelper](https://github.com/kulti/thelper): thelper detects golang test helpers without t.Helper()
- [unparam](https://github.com/mvdan/unparam): Reports unused function parameters and …

go/lint: enable more Go linters in golangci-lint

---

go/lint-project.sh

Two changes in this PR: 
- Forbid print statements in main code (but allowed in tests)
- Allow `panic` in tests, but keep them forbidden in main code

go/lint: forbid print statements in main code and also panic in tests

---

.github/workflows/codeql.yaml
go/lint-project.sh

We use these as test helpers so they don't need tests themselves.

go/lint: ignore "pkg/*test" directories in coverage analysis

---

go/lint-project.sh

Exclude code examples [like these](https://github.com/moov-io/wire/tree/master/examples) from test coverage threshold in `lint-project.sh`.

go: exclude examples from test coverage

---

CONTRIBUTING.md
go/lint-project.sh

For the contributing.md changes:
This one is pretty straightforward. It looks like this wasn't updated when we moved from TravisCI to GitHub Actions. I've updated the reference and its link to point to the Actions tab for this repository.
For the lint-project.sh changes:
While reviewing runs in the CI for some of our services, I noticed the messages shown in the screenshots below that indicate we need to update `skip-dirs` to `exclude-dirs`
With the suggested changes, we no longer see these warning messages

Replace deprecated skip-dirs flag and update contributing.md

---

go/lint-project.sh

`-s` often trips people up
Instead of getting an error like:
```
./tests/code/plugin.go is not formatted
```
The linter will now attempt to format files
```
DEBUG: formatting ./tests/code/plugin.go with gofmt
```

go/lint: auto format files with gofmt that need it
