AUTHORS, AUTHORS.md, README.md, docs/google-cloud.md, docs/kubernetes.md, docs/secrets.md, docs/traefik.md, envs/sbx/README.md, envs/sbx/gcp.tf, envs/sbx/terraform.tf, makefile
Issue: https://github.com/moov-io/infra/issues/16
Preview: https://github.com/adamdecaf/infra/tree/docs
=> docs: initial pass of documentation

.travis.yml
Issue: https://github.com/moov-io/infra/issues/15
=> build: add basic travis-ci config, run promtool

lib/infra/15-grafana.yml, lib/lb/10-traefik-alpha.yml, lib/lb/10-traefik-beta.yml
Issue: https://github.com/moov-io/infra/issues/35
=> all: upgrade nginx to 1.15.6

.travis.yml, pkg/gofuzz/parse.go, pkg/gofuzz/parse_test.go
Issue: https://github.com/moov-io/ach/issues/311
=> pkg/gofuzz: add log line parser for go-fuzz

.travis.yml
Issue: https://github.com/moov-io/infra/issues/14
=> build: run gitleaks in CI

.gitignore, .travis.yml, envs/prod/kubernetes.tf, lib/apps/01-api.yml, lib/apps/10-achfuzz.yml, lib/apps/11-auth.yml, lib/apps/12-paygate.yml, lib/apps/13-ofac-example.yml, lib/apps/13-ofac.yml, lib/apps/14-accounts.yml, lib/apps/15-fed.yml, lib/apps/16-customers.yml, lib/apps/20-qledger.yml, lib/infra/10-oauth2-proxy.yml, lib/infra/12-kube-ingress-index.yml, lib/infra/15-grafana.yml, lib/infra/16-kube-state-metrics.yml, lib/infra/17-cadvisor.yml, lib/infra/18-node-exporter.yml, lib/infra/19-loki.yml, lib/infra/20-promtail.yml, lib/infra/21-domain-exporter.yml, lib/lb/00-namespace.yaml, lib/lb/10-traefik-service.yml, makefile
From a blog post it's easy to run kubeval over our configs now, so let's go ahead and do that.
https://medium.com/@princerachit/validating-kubernetes-deployment-yamls-d46a16a7e664
Issue: #15
=> build: run kubeval over our Kubernetes configs

makefile
See: https://github.com/instrumenta/kubeval/releases/tag/0.15.0
=> build: update kubeval to 0.15.0

go/lint-project.sh, makefile
- https://github.com/zricethezav/gitleaks/releases/v5.0.0
- https://github.com/zricethezav/gitleaks/releases/v5.0.1
=> go/lint: upgrade gitleaks to v5.0.1

go/lint-project.sh
Notes
- gitleaks: https://github.com/zricethezav/gitleaks/releases/tag/v6.1.0
- nancy: https://github.com/sonatype-nexus-community/nancy/releases/tag/v1.0.0
=> go/lint: update gitleaks and nancy 

go/lint-project.sh
Fixes: https://github.com/moov-io/infra/issues/138
=> go/lint: enable nancy once again

modules/alertmanager/deployment.tf, modules/cadvisor/daemonset.tf, modules/customers/deployment.tf, modules/customers/secrets.tf, modules/domain-exporter/deployment.tf, modules/fed/deployment.tf, modules/grafana/deployment.tf, modules/infra-idx/deployment.tf, modules/kube-state-metrics/deployment.tf, modules/loki/loki_deployment.tf, modules/loki/promtail_daemonset.tf, modules/node-exporter/daemonset.tf, modules/oauth2-proxy/deployment.tf, modules/paygate/deployment.tf, modules/prometheus/deployment.tf, modules/traefik-service/service.tf, modules/traefik/deployment.tf, modules/watchman/deployment.tf, tests/terraform-validate.sh
Notes: https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/CHANGELOG.md#200-january-21-2021
=> modules: upgrade to Kubernetes provider v2

lib/lb/10-traefik-alpha.yml, lib/lb/10-traefik-beta.yml, modules/traefik/variables.tf
Changelog: https://github.com/traefik/traefik/releases/tag/v2.4.0 
This might help our issue with oss.moov.io -- https://github.com/traefik/traefik/pull/7458
=> modules/traefik: upgrade to v2.4.x

go/lint-project.sh
More information
- https://github.com/moov-io/infra/pull/159
- https://github.com/sonatype-nexus-community/nancy/issues/217
=> go/lint: upgrade nancy to v1.0.12 with --skip-update-check

envs/oss/moov.io.tf, envs/oss/terraform.tf
DNS and Terraform config. We'll fix our HCL and upgrade the k8s provider to 2.x later.
=> Misc fixes

lib/sales/30-slackin-extended.yml
Upgrade slackin. Already applied via kubectl.
=> sales/slackin: Upgrade version

lib/apps/12-paygate-mysql.yml, lib/apps/13-watchman-mysql.yml, lib/apps/16-customers-mysql.yml
Image registry changed. Will apply to env/oss after approval.
=> Fix bad image reference for mysql-backup

lib/infra/19-loki.yml, lib/infra/20-promtail.yml, modules/loki/variables.tf
Will apply to envs/oss and update refs elsewhere as necessary.
=> Upgrade loki to v2.1.0 in envs/oss and TF modules

lib/infra/19-loki.yml, lib/infra/20-promtail.yml, modules/loki/variables.tf
... In both the OSS environment and module sourced for other environments.
=> Upgrade Loki/Promtail to v2.2.0

lib/infra/14-prometheus.yml, modules/prometheus/variables.tf
Update for modules and OSS env.
=> Upgrade prometheus to v2.25.2

lib/infra/19-loki.yml, lib/infra/20-promtail.yml, modules/loki/variables.tf
For OSS environment and other environments
=> Upgrade Loki to v2.2.1

lib/infra/15-grafana.yml, modules/grafana/variables.tf
For OSS environment and other environments
=> Upgrade Grafana to v7.5.4

.gitignore, go/lint-project.sh
Modify `lint-project.sh` to always force unit tests to run
=> No cache on testing

lib/infra/10-oauth2-proxy.yml, modules/oauth2-proxy/variables.tf
=> Revert back to v7.1.3 for oauth-proxy

docs/fuzzing.md
=> Spelling update

docs/traefik.md
multiple updates for spelling and clarity
I hope this helps!
=> Spelling and grammar updates

docs/kubernetes.md
=> Spelling updates

go/lint-project.sh
Issue: https://github.com/golang/go/issues/49138
=> go/lint: disable race detection for macOS Monterey

go/lint-project.sh
Need to disable nancy for the moment as their own and breaking our builds
=> Need to disable nancy for the moment as their own and breaking our builds

lib/apps/17-imagecashletterwebui.yml
Increasing buffer size to support image data.
=> lib/apps: increase ICL buffer size to 15MB

go/lint-project.sh, makefile
See: https://github.com/golangci/golangci-lint/blob/main/CHANGELOG.md#v200
=> go/lint: update golangci-lint to v2
